version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5002:5002"
    env_file:
      - ./backend/.env
    environment:
      - FLASK_ENV=production
    volumes:
      - ./backend/models:/app/models
      - ./backend/chroma_db:/app/chroma_db
      - ./backend/logs:/app/logs
      - ./backend/events.json:/app/events.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    env_file:
      - ./frontend/.env
    environment:
      - REACT_APP_API_URL=http://localhost:5002
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
